version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "test_pass"
      POSTGRES_USER: "test_user"
      POSTGRES_DB: "test_db"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapi:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./:/src/

volumes:
  pgdata:
