"""init questions models

Revision ID: 16b1830903bf
Revises: 7a126acc1854
Create Date: 2024-07-31 13:42:27.526924

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "16b1830903bf"
down_revision: Union[str, None] = "7a126acc1854"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_topics",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("max_questions", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "test_questions",
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("question", sa.String(), nullable=False),
        sa.Column("correct_answer", sa.Integer(), nullable=False),
        sa.Column("related_rule_id", sa.String(), nullable=True),
        sa.Column(
            "for_license",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "A",
                    "A1",
                    "BE",
                    "B",
                    "B1",
                    "CE",
                    "C",
                    "C1",
                    "C1E",
                    "DE",
                    "D",
                    "D1",
                    "D1E",
                    "T",
                    name="driverlicense",
                    create_type=False,
                )
            ),
            nullable=True,
        ),
        sa.Column("answer_1", sa.String(), nullable=False),
        sa.Column("answer_2", sa.String(), nullable=False),
        sa.Column("answer_3", sa.String(), nullable=True),
        sa.Column("answer_4", sa.String(), nullable=True),
        sa.Column("answer_5", sa.String(), nullable=True),
        sa.Column("has_image", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["test_topics.id"],
        ),
        sa.PrimaryKeyConstraint("topic_id", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_questions")
    op.drop_table("test_topics")
    # ### end Alembic commands ###
